<?xml version="1.0" encoding="utf-8"?><Database Name="qltranhsonmai" Class="qlBanHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-CI36P6F\SQLEXPRESS;Initial Catalog=qltranhsonmai;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="qltranhsonmaiConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tranhsonmai" Member="tranhsonmais">
    <Type Name="tranhsonmai">
      <Column Name="Matranhsonmai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tentranhsonmai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AnhMinhHoa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaitranhsonmai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tranhsonmai_CTDatHang" Member="CTDatHangs" ThisKey="Matranhsonmai" OtherKey="Matranhsonmai" Type="CTDatHang" />
      <Association Name="Loaitranhsonmai_tranhsonmai" Member="Loaitranhsonmai" ThisKey="MaLoaitranhsonmai" OtherKey="MaLoaitranhsonmai" Type="Loaitranhsonmai" IsForeignKey="true" />
      <Association Name="NhaCungCap_tranhsonmai" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDatHang" Member="CTDatHangs">
    <Type Name="CTDatHang">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Matranhsonmai" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="tranhsonmai_CTDatHang" Member="tranhsonmai" ThisKey="Matranhsonmai" OtherKey="Matranhsonmai" Type="tranhsonmai" IsForeignKey="true" />
      <Association Name="DonDatHang_CTDatHang" Member="DonDatHang" ThisKey="MaHD" OtherKey="MaHD" Type="DonDatHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonDatHang_CTDatHang" Member="CTDatHangs" ThisKey="MaHD" OtherKey="MaHD" Type="CTDatHang" />
      <Association Name="KhachHang_DonDatHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_DonDatHang" Member="DonDatHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonDatHang" />
    </Type>
  </Table>
  <Table Name="dbo.Loaitranhsonmai" Member="Loaitranhsonmais">
    <Type Name="Loaitranhsonmai">
      <Column Name="MaLoaitranhsonmai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaitranhsonmai" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Loaitranhsonmai_tranhsonmai" Member="tranhsonmais" ThisKey="MaLoaitranhsonmai" OtherKey="MaLoaitranhsonmai" Type="tranhsonmai" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_tranhsonmai" Member="tranhsonmais" ThisKey="MaNCC" OtherKey="MaNCC" Type="tranhsonmai" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassAdmin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>